# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
