# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='codigo_establecimiento',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
    ]
