# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171129_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
