# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171130_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='region',
            field=models.IntegerField(),
        ),
    ]
